### ISSUE TITLE
Feedback on Milestone #2

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS-2018-19/Colourblind8#51]
Good work team! You've done a great job organizing and building your repo. A few comments:

- Nice work using branches and issues with your workflow
- All tests path except for one passed. The test that failed (`test_input` located in `test_histogram.py`) spat out this error when I used `pytest`: "fixture 'y' not found". Did you also receive this error? It may have been due to how my personal python environment is set up.
- Related to this issue, we are asking that for future versions of your functions you attach, in a new folder, a screenshot of your `pytest` output.
- Good job with your documentation and commenting your functions. Your README is easily navigated and the examples of outputted graphs are helpful. 
- Is there a reason you put all of your functions in the same python script? As opposed to different scripts? I suppose it doesn't matter but it might make your package a little more readable to split it up.

Thanks for the good work!

**Comment by sabrinatkk** [comment]
Hi @rainerlempert , 

As we have responded you in person last Tuesday, I think we can close this issue now. 

Thank you for your feedback!

@sabrinatkk  @ian-flores @hfboyce
